/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package museos;

import java.awt.Desktop;
import java.net.URL;

/**
 *
 * @author galleta
 */
public class FrameMuseos extends javax.swing.JFrame {
    /*Se crea un objeto para el museo que se quiere encontrar*/

    Museo museoEncontrado;

    /**
     * Creates new form FrameMuseos
     */
    public FrameMuseos() {
        initComponents();

        /*método para ocular los textos de los elementos*/
        ocultarelEmentos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreMuseo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        labelMuseo = new javax.swing.JLabel();
        txtMEncontradoNombre = new javax.swing.JLabel();
        labelHorario = new javax.swing.JLabel();
        txtMEncontradoHorario = new javax.swing.JLabel();
        labelCosto = new javax.swing.JLabel();
        txtMEncontradoCosto = new javax.swing.JLabel();
        labelDireccion = new javax.swing.JLabel();
        txtMEncontradoDireccion = new javax.swing.JLabel();
        labelDescripcion = new javax.swing.JLabel();
        txtMEncontradoDescripcion = new javax.swing.JLabel();
        txtMensajeError = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnMapa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel1.setText("Museos DF");

        jLabel2.setText("Nombre del museo:");

        txtNombreMuseo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreMuseoActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        labelMuseo.setText("Museo:");

        txtMEncontradoNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtMEncontradoNombre.setText("jLabel4");

        labelHorario.setText("Horario:");

        txtMEncontradoHorario.setText("jLabel5");

        labelCosto.setText("Costo:");

        txtMEncontradoCosto.setText("jLabel6");
        txtMEncontradoCosto.setAutoscrolls(true);

        labelDireccion.setText("Dirección:");

        txtMEncontradoDireccion.setText("jLabel7");

        labelDescripcion.setText("Descripción:");

        txtMEncontradoDescripcion.setText("jLabel8");

        txtMensajeError.setForeground(new java.awt.Color(204, 51, 0));
        txtMensajeError.setText("jLabel8");

        jButton1.setText("Ver Todos los museos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnMapa.setText("Mapa");
        btnMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMapaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMensajeError)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNombreMuseo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addComponent(btnBuscar)
                                .addGap(74, 74, 74))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelDireccion)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtMEncontradoDireccion))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelCosto)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtMEncontradoCosto))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelHorario)
                                        .addComponent(labelMuseo))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtMEncontradoNombre)
                                        .addComponent(txtMEncontradoHorario)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelDescripcion)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtMEncontradoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnMapa)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreMuseo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMensajeError)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMuseo)
                    .addComponent(txtMEncontradoNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHorario)
                    .addComponent(txtMEncontradoHorario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCosto)
                    .addComponent(txtMEncontradoCosto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDireccion)
                    .addComponent(txtMEncontradoDireccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDescripcion)
                    .addComponent(txtMEncontradoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMapa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>                        

    /*Este método lo da el Swing, para las cosas que tenga que hacer el botón buscar*/
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {                                          

        /*Se crea una instancia de la clase Datos, que inicializó la lista de museos*/
        Datos datos = new Datos();

        /*Se llama al métpdp buscar para que compare los nombres.
         con txtNombreMuseo.getText() se obtiene lo que el usuario escribio*/
        museoEncontrado = datos.buscarMuseoPorNombre(txtNombreMuseo.getText());
        if (museoEncontrado != null) {
            /*si encontro coincidencias que escriba en los textos, da los datos del museo*/
            System.out.println(museoEncontrado.toString());
            txtMEncontradoCosto.setText(museoEncontrado.getCosto());
            txtMEncontradoNombre.setText(museoEncontrado.getNombre());
            txtMEncontradoHorario.setText(museoEncontrado.getHorario());
            txtMEncontradoDescripcion.setText(museoEncontrado.getDescripcion());
            txtMEncontradoDireccion.setText(museoEncontrado.getDelegacion() + ", " + museoEncontrado.getColonia() + ", " + museoEncontrado.getCalle() + ", " + museoEncontrado.getNumero());
            /*el mensaje de error que no se vea*/
            txtMensajeError.setVisible(false);
            mostrarEmentos();
        } else {
            /*se llama al método ocultar para que no muestre los textos cuando
             no se encuentra nada*/
            ocultarelEmentos();
            txtMensajeError.setText("No se encontró, intenta de nuevo");
            txtMensajeError.setVisible(true);
        }
    }                                         

    //ABRIR LA VENTANA 2
    //boton ver todos los museos
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        //instanciar la clase de la ventana 2
        TablaMuseos ventanaTabla = new TablaMuseos();
        //se llama al metodo que crea la ventana
        ventanaTabla.ShowScreenTabla();
    }                                        

    /*Boton de abrir el mapa*/
    private void btnMapaActionPerformed(java.awt.event.ActionEvent evt) {                                        
        /*abrir el navegador con la url del mapa*/
     try {
          
         //sin zoom
       //  Desktop.getDesktop().browse(new URL("https://www.google.com/maps/place/"+museoEncontrado.getAltitud()+","+museoEncontrado.getLongitud()).toURI());
         //con zoom
       String zoom="80z";
         Desktop.getDesktop().browse(new URL("https://www.google.com/maps/place/"+museoEncontrado.getAltitud()+","+museoEncontrado.getLongitud()+"/@"+museoEncontrado.getAltitud()+","+museoEncontrado.getLongitud()+","+zoom).toURI());
         
        } catch (Exception e) {
            e.printStackTrace();
        }
    }                                       

    private void txtNombreMuseoActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMuseos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMuseos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMuseos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMuseos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMuseos().setVisible(true);
            }
        });
    }

    /*método para ocular los textos de los elementos*/
    public void ocultarelEmentos() {
        txtMEncontradoDescripcion.setVisible(false);
        txtMEncontradoDireccion.setVisible(false);
        txtMEncontradoCosto.setVisible(false);
        txtMEncontradoHorario.setVisible(false);
        txtMEncontradoNombre.setVisible(false);
        txtMensajeError.setVisible(false);
        labelHorario.setVisible(false);
        labelMuseo.setVisible(false);
        labelDireccion.setVisible(false);
        labelDescripcion.setVisible(false);
        labelCosto.setVisible(false);
        btnMapa.setVisible(false);
    }

    /*método para mostrar los textos de los elementos*/
    public void mostrarEmentos() {
        txtMEncontradoDescripcion.setVisible(true);
        txtMEncontradoDireccion.setVisible(true);
        txtMEncontradoCosto.setVisible(true);
        txtMEncontradoHorario.setVisible(true);
        txtMEncontradoNombre.setVisible(true);
        labelHorario.setVisible(true);
        labelMuseo.setVisible(true);
        labelDireccion.setVisible(true);
        labelDescripcion.setVisible(true);
        labelCosto.setVisible(true);
        btnMapa.setVisible(true);
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnMapa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelCosto;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelHorario;
    private javax.swing.JLabel labelMuseo;
    private javax.swing.JLabel txtMEncontradoCosto;
    private javax.swing.JLabel txtMEncontradoDescripcion;
    private javax.swing.JLabel txtMEncontradoDireccion;
    private javax.swing.JLabel txtMEncontradoHorario;
    private javax.swing.JLabel txtMEncontradoNombre;
    private javax.swing.JLabel txtMensajeError;
    private javax.swing.JTextField txtNombreMuseo;
    // End of variables declaration                   
}
