/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package museos;

import java.util.ArrayList;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author galleta
 */
public class TablaMuseos extends javax.swing.JFrame {
 ArrayList<Museo> listaMuseos= new ArrayList<Museo>();
    /**
     * Creates new form NewJFrame
     */
    public TablaMuseos() {
        initComponents();
       
         Datos datos = new Datos();
        listaMuseos= datos.listaMuseos;
        //crear tipo de objeto DefaultTableModel para llenar la tabla
        DefaultTableModel modelo= (DefaultTableModel)jTable1.getModel();
       
        Object[] fila = new Object[modelo.getColumnCount()];
        
        //iterar lista de museos, para recorrerlos y mostrarlos en la tabla
        for (int i = 0; i < listaMuseos.size(); i++) {
            fila[0]= i+1;//número del museo, +1 porque el inidice inicia en 0
            fila[1]= listaMuseos.get(i).getNombre();
            fila[2]= listaMuseos.get(i).getHorario();
            fila[3]= listaMuseos.get(i).getDelegacion();
            //se agrega la fila al modelo
            modelo.addRow(fila);
        }
         //new JScrollPane(this.jTable1, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num", "Nombre", "Horario", "Delegacion"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    /*métpdp que crea la ventana*/
    public static void ShowScreenTabla() {      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaMuseos().setVisible(true);
                
            }
        });
        
        
    }

    // Variables declaration - do not modify                     
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration                   
}
